require 'roxml'
require 'nokogiri'
require 'logger'
require 'active_model'

#== Base files

require 'quickeebooks/extensions/roxml'
require 'quickeebooks/errors'
require 'quickeebooks/collection'

#== Shared

# Services
require 'quickeebooks/shared/service/filter'
require 'quickeebooks/shared/service/access_token'
require 'quickeebooks/shared/service/sort'
require 'quickeebooks/shared/service/base'
require 'quickeebooks/shared/service/request'

#== Online

# Models
require 'quickeebooks/online/model/intuit_type'
require 'quickeebooks/online/model/company_meta_data'
require 'quickeebooks/online/model/customer'
require 'quickeebooks/online/model/account'
require 'quickeebooks/online/model/invoice'
require 'quickeebooks/online/model/invoice_header'
require 'quickeebooks/online/model/invoice_line_item'
require 'quickeebooks/online/model/item'
require 'quickeebooks/online/model/unit_price'
require 'quickeebooks/online/model/meta_data'
require 'quickeebooks/online/model/price'
require 'quickeebooks/online/model/account_reference'
require 'quickeebooks/online/model/payment'
require 'quickeebooks/online/model/payment_header'
require 'quickeebooks/online/model/payment_line_item'
require 'quickeebooks/online/model/payment_detail'
require 'quickeebooks/online/model/credit_card'
require 'quickeebooks/online/model/credit_charge_info'
require 'quickeebooks/online/model/credit_charge_response'
require 'quickeebooks/online/model/sales_term'

# Services
require 'quickeebooks/online/service/filter'
require 'quickeebooks/online/service/pagination'
require 'quickeebooks/online/service/sort'
require 'quickeebooks/online/service/company_meta_data'
require 'quickeebooks/online/service/customer'
require 'quickeebooks/online/service/account'
require 'quickeebooks/online/service/invoice'
require 'quickeebooks/online/service/item'
require 'quickeebooks/online/service/entitlement'
require 'quickeebooks/online/service/payment'
require 'quickeebooks/online/service/access_token'
require 'quickeebooks/online/service/sales_term'

#== Windows

# Models
require 'quickeebooks/windows/model/intuit_type'
require 'quickeebooks/windows/model/id'
require 'quickeebooks/windows/model/custom_field'
require 'quickeebooks/windows/model/price'
require 'quickeebooks/windows/model/customer'
require 'quickeebooks/windows/model/account'
require 'quickeebooks/windows/model/item'
require 'quickeebooks/windows/model/invoice'
require 'quickeebooks/windows/model/invoice_header'
require 'quickeebooks/windows/model/invoice_line_item'
require 'quickeebooks/windows/model/address'
require 'quickeebooks/windows/model/rest_response'
require 'quickeebooks/windows/model/success'
require 'quickeebooks/windows/model/error'
require 'quickeebooks/windows/model/object_ref'
require 'quickeebooks/windows/model/sales_rep'
require 'quickeebooks/windows/model/vendor'
require 'quickeebooks/windows/model/vendor_id'
require 'quickeebooks/windows/model/external_key'
require 'quickeebooks/windows/model/ship_method'
require 'quickeebooks/windows/model/sales_tax'
require 'quickeebooks/windows/model/customer_msg'
require 'quickeebooks/windows/model/company_meta_data'
require 'quickeebooks/windows/model/payment'
require 'quickeebooks/windows/model/payment_header'
require 'quickeebooks/windows/model/payment_line_item'
require 'quickeebooks/windows/model/payment_detail'
require 'quickeebooks/windows/model/credit_card'
require 'quickeebooks/windows/model/credit_charge_info'
require 'quickeebooks/windows/model/credit_charge_response'
require 'quickeebooks/windows/model/clazz'
require 'quickeebooks/windows/model/sales_receipt_header'
require 'quickeebooks/windows/model/sales_receipt_line_item'
require 'quickeebooks/windows/model/sales_receipt'


# Services
require 'quickeebooks/windows/service/filter'
require 'quickeebooks/windows/service/sort'
require 'quickeebooks/windows/service/base'
require 'quickeebooks/windows/service/account'
require 'quickeebooks/windows/service/customer'
require 'quickeebooks/windows/service/item'
require 'quickeebooks/windows/service/invoice'
require 'quickeebooks/windows/service/sales_rep'
require 'quickeebooks/windows/service/sales_receipt'
require 'quickeebooks/windows/service/ship_method'
require 'quickeebooks/windows/service/sales_tax'
require 'quickeebooks/windows/service/customer_msg'
require 'quickeebooks/windows/service/company_meta_data'
require 'quickeebooks/windows/service/payment'
require 'quickeebooks/windows/service/clazz'
require 'quickeebooks/windows/service/access_token'
